#file "/shaders.properties"

#replace "# Screen Setup"
photonics.supported=true
photonics.enabled=true
photonics.maxLights=1000
photonics.maxSamples=20
uniform.float.ph_debug_lighting_master_scale=1.0
uniform.float.ph_debug_cast_light_pixel_size=8.0
uniform.float.ph_debug_cast_light_value_steps=18.0
uniform.float.ph_debug_cast_light_threshold=0.001

# Screen Setup
#endreplace
