package at.redi2go.photonic.client.api;

import net.irisshaders.iris.helpers.OptionalBoolean;

public interface PhotonicsProperties {
   float DEFAULT_RENDER_SCALE = 1.0F;
   int DEFAULT_MAX_LIGHTS = 1000;
   int DEFAULT_MAX_SAMPLES = 20;
   float DEFAULT_MIN_TRACED_LIGHT_LUMA = 0.001F;
   AlphaMode DEFAULT_ALPHA_MODE = AlphaMode.NONE;
   int DEFAULT_LIGHTTREE_INITIAL_SAMPLES = 8;
   int DEFAULT_LIGHTTREE_SPATIAL_REUSE_SAMPLES = 5;
   float DEFAULT_LIGHTTREE_SPATIAL_REUSE_RADIUS = 10.0F;
   int DEFAULT_LIGHTTREE_ACCUMULATION_FRAMES = 15;
   int DEFAULT_LIGHTTREE_DENOISER_PASSES = 5;
   int DEFAULT_NRD_ATROUS_PASSES = 5;
   float DEFAULT_RESTIR_DEPTH_THRESHOLD = 0.1f;
   float DEFAULT_RESTIR_NORMAL_THRESHOLD = 0.5f;
   int DEFAULT_RESTIR_TEMPORAL_MAX_HISTORY = 20;
   float DEFAULT_RESTIR_TEMPORAL_DEPTH_THRESHOLD = 0.1f;
   float DEFAULT_RESTIR_TEMPORAL_NORMAL_THRESHOLD = 0.5f;
   int DEFAULT_RESTIR_SPATIAL_SAMPLE_COUNT = 1;
   float DEFAULT_RESTIR_SPATIAL_RADIUS = 32.0f;
   float DEFAULT_RESTIR_SPATIAL_DEPTH_THRESHOLD = 0.1f;
   float DEFAULT_RESTIR_SPATIAL_NORMAL_THRESHOLD = 0.5f;
   int DEFAULT_RESTIR_VISIBILITY_MAX_AGE = 4;
   float DEFAULT_RESTIR_VISIBILITY_MAX_DISTANCE = 16.0f;
   float DEFAULT_RESTIR_TEMPORAL_BIAS_MODE = 3.0f;
   float DEFAULT_RESTIR_TEMPORAL_PERMUTATION_SAMPLING = 1.0f;
   float DEFAULT_RESTIR_TEMPORAL_VISIBILITY_SHORTCUT = 0.0f;
   float DEFAULT_RESTIR_SPATIAL_BIAS_MODE = 2.0f;
   float DEFAULT_RESTIR_SPATIAL_DISCOUNT_NAIVE = 1.0f;
   float DEFAULT_RESTIR_SPATIAL_MATERIAL_TEST = 1.0f;
   float DEFAULT_RESTIR_SPATIAL_BOOST_SAMPLES = 8.0f;
   float DEFAULT_RESTIR_SPATIAL_TARGET_HISTORY = 0.0f;

   OptionalBoolean isPhotonicsEnabled();
   float getRenderScale();
   int getMaxLights();
   int getMaxSamples();
   float getMinTracedLightLuma();
   AlphaMode getAlphaMode();
   OptionalBoolean isGiEnabled();
   OptionalBoolean isBlockLightEnabled();
   OptionalBoolean isHandheldLightEnabled();
   OptionalBoolean voxelizeLava();
   int getLightTreeInitialSamples();
   int getLightTreeSpatialReuseSamples();
   float getLightTreeSpatialReuseRadius();
   int getLightTreeAccumulationFrames();
   OptionalBoolean useLightTreeSoftShadows();
   int getLightTreeDenoiserPasses();
   int getNrdAtrousPasses();
   float getRestirDepthThreshold();
   float getRestirNormalThreshold();
   int getRestirTemporalMaxHistory();
   float getRestirTemporalDepthThreshold();
   float getRestirTemporalNormalThreshold();
   int getRestirSpatialSampleCount();
   float getRestirSpatialRadius();
   float getRestirSpatialDepthThreshold();
   float getRestirSpatialNormalThreshold();
   int getRestirVisibilityMaxAge();
   float getRestirVisibilityMaxDistance();
   float getRestirTemporalBiasMode();
   float getRestirTemporalPermutationSampling();
   float getRestirTemporalVisibilityShortcut();
   float getRestirSpatialBiasMode();
   float getRestirSpatialDiscountNaive();
   float getRestirSpatialMaterialTest();
   float getRestirSpatialBoostSamples();
   float getRestirSpatialTargetHistory();
}
